### ISSUE TITLE
NoStrip keyword not detected on items

### ISSUE THREAD

**Issue by heromaster** [GAntono/SerialStrip#51]
> I added the "NoStrip" keyword to a few armor items (taking up various slots), but they end up stripping during the main-body stripping sequence. Are there supposed to be keywords that need to be avoided or is the item supposed to be ignored if the "NoStrip" keyword appears on its list?

**Comment by GAntono** [comment]
A byproduct of calling keyword checking functions on the wrong slots and SexLab arrays (bug #53).
Fixed in 0106ceda41b2cc5d7b23c5c83bf751799e681a37
