### ISSUE TITLE
Animations are blocked when not standing but items still will be stripped

### ISSUE THREAD

**Issue by heromaster** [GAntono/SerialStrip#52]
> If triggering the strip sequence while crouched (long press or single tap), the player character will lock in place and the movement controls will be unresponsive for a while (I assume this is the timing for the animation playing). The clothes will eventually come off, yet no animation is shown (because there is no crouch undress animation, I guess). It would probably be a good idea to force the player to stand in a non-combat stance before the stripping sequence, or block stripping while crouched.

**Comment by heromaster** [comment]
We may missed to check if the animations could be played or not.

If not done already we should do something like this

```
If(Actor.PlayIdle)
    ;unequip item here
EndIf
```

**Comment by heromaster** [comment]
If above suggestion doesn't work we should add a pre check if the player is standing and refuse to do anything if the player doesn't meet our preconditions.

**Comment by GAntono** [comment]
For the time being, I've added validation checks to abort animating and stripping if player is running/sneaking/swimming etc.
In later versions we should convert all these checks into

```
If (!PlayerRef.PlayIdle(DefaultIdleProperty)
    Return
EndIf
```

see #57
