### ISSUE TITLE
SerialStripper doesn't look into SexLab strip list or is looking up the wrong list

### ISSUE THREAD

**Issue by heromaster** [GAntono/SerialStrip#53]
> I do have SexLab (v1.58b) settings with certain slots ignored for stripping, but the undressing options aren't enforced.

**Comment by GAntono** [comment]
Code was calling keyword checking functions on the wrong slots (SS-SL slot missmatch).
Fixed in 0106ceda41b2cc5d7b23c5c83bf751799e681a37
